version: "3"

services:

  node_back:
    image: node:19-alpine3.16
    container_name: node_back
    depends_on:
      - mongodb
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
#    command: node

    ports:
      - 3000:3000
      - 9000:9000
    volumes:
      - .:/home/node

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file: ./db/.env
#    environment:
#      - MONGO_INITRD_ROOT_USERNAME=$DB_USER
#      - MONGO_INITRD_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

  node_front:
    container_name: node_front
    depends_on:
      - node_back
    build:
      context: ./
      dockerfile: front/Dockerfile.node
    working_dir: /home/node
    tty: true
    stdin_open: true
#    command: alias alias_name="command_to_run"


    ports:
      - "8080:8080"
    volumes:
      - ./front:/home/node

volumes:
  mongodb: